/**
 * scripts/rotate-public-tokens.ts
 *
 * Safely rotates the `publicToken` on Proposal, Invoice, and CallSheet records
 * that still hold a CUID v1 token (generated by the old @default(cuid()) schema).
 *
 * ── Modes ────────────────────────────────────────────────────────────────────
 *   --dry-run   (default) Print what WOULD be rotated.  No DB writes.
 *   --live      Actually write new tokens.  Confirm the prompt first.
 *   --all       Include SENT/VIEWED/APPROVED records (breaks live shared links).
 *               Without this flag only DRAFT records are rotated (safe).
 *
 * ── Usage ────────────────────────────────────────────────────────────────────
 *   # Check what would change (safe, no writes):
 *   npx ts-node --project tsconfig.json scripts/rotate-public-tokens.ts
 *
 *   # Rotate DRAFT records only (safest starting point):
 *   npx ts-node --project tsconfig.json scripts/rotate-public-tokens.ts --live
 *
 *   # Rotate ALL records (breaks existing shared links — notify clients first):
 *   npx ts-node --project tsconfig.json scripts/rotate-public-tokens.ts --live --all
 *
 * ── Prerequisite ─────────────────────────────────────────────────────────────
 *   Run prisma/migrations/20260614000003_secure_public_tokens/migration.sql
 *   in Neon BEFORE running this script.
 *
 * ── What counts as a CUID? ───────────────────────────────────────────────────
 *   CUID v1 tokens start with 'c', are 25 chars long, and contain only
 *   lowercase alphanumerics.  UUID v4 tokens are 36 chars with hyphens.
 *   The regex below is conservative: anything that looks like a CUID is rotated.
 */

import { PrismaClient } from '@prisma/client'
import * as readline from 'readline'

const prisma = new PrismaClient()

// CUID v1: starts with 'c', 25 lowercase alphanumeric chars
const CUID_RE = /^c[a-z0-9]{24}$/

function isCuid(token: string): boolean {
  return CUID_RE.test(token)
}

function generateUUID(): string {
  return crypto.randomUUID()
}

async function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout })
  return new Promise(resolve => {
    rl.question(`${question} [y/N] `, answer => {
      rl.close()
      resolve(answer.trim().toLowerCase() === 'y')
    })
  })
}

async function main() {
  const args    = process.argv.slice(2)
  const dryRun  = !args.includes('--live')
  const rotateAll = args.includes('--all')

  console.log('\n── Rotate Public Tokens ────────────────────────────────────────')
  console.log(`   Mode  : ${dryRun ? 'DRY RUN (pass --live to write)' : '⚠  LIVE — will write to DB'}`)
  console.log(`   Scope : ${rotateAll ? '⚠  ALL records (shared links will break)' : 'DRAFT only (safe)'}`)
  console.log('────────────────────────────────────────────────────────────────\n')

  if (!dryRun && rotateAll) {
    console.log('WARNING: --live --all will invalidate every public link that has')
    console.log('already been shared with clients (proposals, invoices, call sheets).')
    console.log('You should notify clients and re-send links after this rotation.\n')
    const ok = await confirm('Are you sure you want to continue?')
    if (!ok) { console.log('Aborted.'); process.exit(0) }
  }

  // ── Proposals ──────────────────────────────────────────────────────────────
  const proposals = await prisma.proposal.findMany({
    where: rotateAll ? {} : { status: 'DRAFT' },
    select: { id: true, publicToken: true, status: true, title: true },
    orderBy: { createdAt: 'asc' },
  })
  const staleProposals = proposals.filter(p => isCuid(p.publicToken))

  console.log(`Proposals — found ${staleProposals.length} with CUID tokens (of ${proposals.length} in scope)`)

  for (const p of staleProposals) {
    const newToken = generateUUID()
    if (dryRun) {
      console.log(`  [DRY]  ${p.id}  "${p.title}" (${p.status})  ${p.publicToken} → ${newToken}`)
    } else {
      await prisma.proposal.update({ where: { id: p.id }, data: { publicToken: newToken } })
      console.log(`  ✓  ${p.id}  "${p.title}" (${p.status})`)
    }
  }

  // ── Invoices ───────────────────────────────────────────────────────────────
  const invoices = await prisma.invoice.findMany({
    where: rotateAll ? {} : { status: 'DRAFT' },
    select: { id: true, publicToken: true, status: true, number: true },
    orderBy: { createdAt: 'asc' },
  })
  const staleInvoices = invoices.filter(i => isCuid(i.publicToken))

  console.log(`\nInvoices — found ${staleInvoices.length} with CUID tokens (of ${invoices.length} in scope)`)

  for (const i of staleInvoices) {
    const newToken = generateUUID()
    if (dryRun) {
      console.log(`  [DRY]  ${i.id}  #${i.number} (${i.status})  ${i.publicToken} → ${newToken}`)
    } else {
      await prisma.invoice.update({ where: { id: i.id }, data: { publicToken: newToken } })
      console.log(`  ✓  ${i.id}  #${i.number} (${i.status})`)
    }
  }

  // ── Call Sheets ────────────────────────────────────────────────────────────
  const callSheets = await prisma.callSheet.findMany({
    where: rotateAll ? {} : { status: 'DRAFT' },
    select: { id: true, publicToken: true, status: true, title: true },
    orderBy: { createdAt: 'asc' },
  })
  const staleCallSheets = callSheets.filter(cs => isCuid(cs.publicToken))

  console.log(`\nCall Sheets — found ${staleCallSheets.length} with CUID tokens (of ${callSheets.length} in scope)`)

  for (const cs of staleCallSheets) {
    const newToken = generateUUID()
    if (dryRun) {
      console.log(`  [DRY]  ${cs.id}  "${cs.title}" (${cs.status})  ${cs.publicToken} → ${newToken}`)
    } else {
      await prisma.callSheet.update({ where: { id: cs.id }, data: { publicToken: newToken } })
      console.log(`  ✓  ${cs.id}  "${cs.title}" (${cs.status})`)
    }
  }

  // ── Summary ────────────────────────────────────────────────────────────────
  const total = staleProposals.length + staleInvoices.length + staleCallSheets.length
  console.log('\n────────────────────────────────────────────────────────────────')
  if (dryRun) {
    console.log(`DRY RUN complete.  ${total} token(s) would be rotated.`)
    console.log('Re-run with --live to apply changes.')
  } else {
    console.log(`✓ Done.  ${total} token(s) rotated to UUID v4.`)
    if (!rotateAll) {
      console.log('\nNote: only DRAFT records were rotated.  SENT/APPROVED records')
      console.log('still have CUID tokens.  Re-run with --live --all to rotate')
      console.log('everything (invalidates shared links).')
    }
  }
  console.log('────────────────────────────────────────────────────────────────\n')
}

main()
  .catch(err => { console.error(err); process.exit(1) })
  .finally(() => prisma.$disconnect())
